### ISSUE TITLE
After moving to v0.12 it fails to build on macos

### ISSUE THREAD

**Issue by alisomay** [leexgone/uiautomation-rs#74]
State of `cargo.toml`

```toml
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_UI_Input",
    "Win32_UI_WindowsAndMessaging",
] }
# Version 0.11.5 is the latest version at 13.06.2024 that supports building on non windows platforms, check updates frequently probably this issue will pass.
# uiautomation = { version = "=0.11.5" }
uiautomation = { version = "0.12" }
```

Errors:

```
error[E0425]: cannot find function, tuple struct or tuple variant `VarBstrFromR8` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:751:30
    |
751 |                     VT_R8 => VarBstrFromR8(self.get_data().dblVal, 0, 0)?,
    |                              ^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarBstrFromUI1` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:752:31
    |
752 |                     VT_UI1 => VarBstrFromUI1(self.get_data().bVal, 0, 0)?,
    |                               ^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarBstrFromUI2` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:753:31
    |
753 |                     VT_UI2 => VarBstrFromUI2(self.get_data().uiVal, 0, 0)?,
    |                               ^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarBstrFromUI4` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:754:41
    |
754 |                     VT_UI4 | VT_UINT => VarBstrFromUI4(self.get_data().ulVal, 0, 0)?,
    |                                         ^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarBstrFromUI8` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:755:31
    |
755 |                     VT_UI8 => VarBstrFromUI8(self.get_data().ullVal, 0, 0)?,
    |                               ^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI1FromBool` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:826:47
    |
826 |                 VT_BOOL     => variant_as_i1!(VarI1FromBool, self.as_bool()), 
    |                                               ^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI1FromCy` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:827:47
    |
827 |                 VT_CY       => variant_as_i1!(VarI1FromCy, self.as_currency()), 
    |                                               ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI1FromDate` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:828:47
    |
828 |                 VT_DATE     => variant_as_i1!(VarI1FromDate, self.get_data().date),
    |                                               ^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI1FromDec` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:829:47
    |
829 |                 VT_DECIMAL  => variant_as_i1!(VarI1FromDec, &self.as_decimal()),
    |                                               ^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI1FromDisp` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:832:21
    |
832 |                     VarI1FromDisp(disp, 0, pc)?;
    |                     ^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI1FromI2` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:838:43
    |
838 |                 VT_I2   => variant_as_i1!(VarI1FromI2, self.get_data().iVal),
    |                                           ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI1FromI4` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:839:51
    |
839 |                 VT_I4 | VT_INT  => variant_as_i1!(VarI1FromI4, self.get_data().lVal),
    |                                                   ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI1FromI8` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:840:43
    |
840 |                 VT_I8   => variant_as_i1!(VarI1FromI8, self.get_data().llVal),
    |                                           ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI1FromR4` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:841:43
    |
841 |                 VT_R4   => variant_as_i1!(VarI1FromR4, self.get_data().fltVal),
    |                                           ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI1FromR8` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:842:43
    |
842 |                 VT_R8   => variant_as_i1!(VarI1FromR8, self.get_data().dblVal),
    |                                           ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI1FromStr` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:847:21
    |
847 |                     VarI1FromStr(&str, 0, 0, pc)?;
    |                     ^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI1FromUI1` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:850:43
    |
850 |                 VT_UI1  => variant_as_i1!(VarI1FromUI1, self.get_data().bVal),
    |                                           ^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI1FromUI2` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:851:43
    |
851 |                 VT_UI2  => variant_as_i1!(VarI1FromUI2, self.get_data().uiVal),
    |                                           ^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI1FromUI4` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:852:52
    |
852 |                 VT_UI4 | VT_UINT => variant_as_i1!(VarI1FromUI4, self.get_data().ulVal),
    |                                                    ^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI1FromUI8` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:853:43
    |
853 |                 VT_UI8  => variant_as_i1!(VarI1FromUI8, self.get_data().ullVal),
    |                                           ^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI2FromBool` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:882:32
    |
882 |                 VT_BOOL     => VarI2FromBool(self.as_bool())?, 
    |                                ^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI2FromCy` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:883:49
    |
883 |                 VT_CY       => variant_as_type!(VarI2FromCy, i16, self.as_currency()), 
    |                                                 ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI2FromDate` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:884:32
    |
884 |                 VT_DATE     => VarI2FromDate(self.get_data().date)?,
    |                                ^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI2FromDec` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:885:32
    |
885 |                 VT_DECIMAL  => VarI2FromDec(&self.as_decimal())?,
    |                                ^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI2FromDisp` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:886:56
    |
886 |                 VT_DISPATCH => dispatch_as_type!(self, VarI2FromDisp),
    |                                                        ^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI2FromI1` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:887:32
    |
887 |                 VT_I1       => VarI2FromI1(self.get_data().cVal)?,
    |                                ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI2FromI4` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:889:36
    |
889 |                 VT_I4 | VT_INT  => VarI2FromI4(self.get_data().lVal)?,
    |                                    ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI2FromI8` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:890:32
    |
890 |                 VT_I8       => VarI2FromI8(self.get_data().llVal)?,
    |                                ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI2FromR4` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:891:32
    |
891 |                 VT_R4       => VarI2FromR4(self.get_data().fltVal)?,
    |                                ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI2FromR8` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:892:32
    |
892 |                 VT_R8       => VarI2FromR8(self.get_data().dblVal)?,
    |                                ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI2FromStr` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:893:66
    |
893 |                 VT_BSTR | VT_LPWSTR | VT_LPSTR  => variant_atoi!(VarI2FromStr, self.get_string()?), 
    |                                                                  ^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI2FromUI1` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:894:32
    |
894 |                 VT_UI1      => VarI2FromUI1(self.get_data().bVal)?,
    |                                ^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI2FromUI2` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:895:32
    |
895 |                 VT_UI2      => VarI2FromUI2(self.get_data().uiVal)?,
    |                                ^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI2FromUI4` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:896:40
    |
896 |                 VT_UI4 | VT_UINT    => VarI2FromUI4(self.get_data().ulVal)?,
    |                                        ^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI2FromUI8` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:897:32
    |
897 |                 VT_UI8      => VarI2FromUI8(self.get_data().ullVal)?,
    |                                ^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI4FromBool` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:926:32
    |
926 |                 VT_BOOL     => VarI4FromBool(self.as_bool())?, 
    |                                ^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI4FromCy` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:927:32
    |
927 |                 VT_CY       => VarI4FromCy(self.as_currency())?, 
    |                                ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI4FromDate` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:928:32
    |
928 |                 VT_DATE     => VarI4FromDate(self.get_data().date)?,
    |                                ^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI4FromDec` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:929:32
    |
929 |                 VT_DECIMAL  => VarI4FromDec(&self.as_decimal())?,
    |                                ^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI4FromDisp` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:930:56
    |
930 |                 VT_DISPATCH => dispatch_as_type!(self, VarI4FromDisp),
    |                                                        ^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI4FromI1` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:931:32
    |
931 |                 VT_I1       => VarI4FromI1(self.get_data().cVal)?,
    |                                ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI4FromI2` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:932:32
    |
932 |                 VT_I2       => VarI4FromI2(self.get_data().iVal)?,
    |                                ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI4FromI8` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:934:32
    |
934 |                 VT_I8       => VarI4FromI8(self.get_data().llVal)?,
    |                                ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI4FromR4` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:935:32
    |
935 |                 VT_R4       => VarI4FromR4(self.get_data().fltVal)?,
    |                                ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI4FromR8` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:936:32
    |
936 |                 VT_R8       => VarI4FromR8(self.get_data().dblVal)?,
    |                                ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI4FromStr` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:937:66
    |
937 |                 VT_BSTR | VT_LPWSTR | VT_LPSTR  => variant_atoi!(VarI4FromStr, self.get_string()?), 
    |                                                                  ^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI4FromUI1` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:938:32
    |
938 |                 VT_UI1      => VarI4FromUI1(self.get_data().bVal)?,
    |                                ^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI4FromUI2` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:939:32
    |
939 |                 VT_UI2      => VarI4FromUI2(self.get_data().uiVal)?,
    |                                ^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI4FromUI4` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:940:40
    |
940 |                 VT_UI4 | VT_UINT    => VarI4FromUI4(self.get_data().ulVal)?,
    |                                        ^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI4FromUI8` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:941:32
    |
941 |                 VT_UI8      => VarI4FromUI8(self.get_data().ullVal)?,
    |                                ^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI8FromBool` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:970:32
    |
970 |                 VT_BOOL     => VarI8FromBool(self.as_bool())?, 
    |                                ^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI8FromCy` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:971:32
    |
971 |                 VT_CY       => VarI8FromCy(self.as_currency())?, 
    |                                ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI8FromDate` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:972:32
    |
972 |                 VT_DATE     => VarI8FromDate(self.get_data().date)?,
    |                                ^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI8FromDec` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:973:32
    |
973 |                 VT_DECIMAL  => VarI8FromDec(&self.as_decimal())?, 
    |                                ^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI8FromDisp` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:974:56
    |
974 |                 VT_DISPATCH => dispatch_as_type!(self, VarI8FromDisp),
    |                                                        ^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI8FromI1` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:975:32
    |
975 |                 VT_I1       => VarI8FromI1(self.get_data().cVal)?,
    |                                ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI8FromI2` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:976:32
    |
976 |                 VT_I2       => VarI8FromI2(self.get_data().iVal)?,
    |                                ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI8FromR4` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:979:32
    |
979 |                 VT_R4       => VarI8FromR4(self.get_data().fltVal)?,
    |                                ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI8FromR8` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:980:32
    |
980 |                 VT_R8       => VarI8FromR8(self.get_data().dblVal)?,
    |                                ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI8FromStr` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:981:66
    |
981 |                 VT_BSTR | VT_LPWSTR | VT_LPSTR  => variant_atoi!(VarI8FromStr, self.get_string()?),
    |                                                                  ^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI8FromUI1` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:982:32
    |
982 |                 VT_UI1      => VarI8FromUI1(self.get_data().bVal)?,
    |                                ^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI8FromUI2` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:983:32
    |
983 |                 VT_UI2      => VarI8FromUI2(self.get_data().uiVal)?,
    |                                ^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI8FromUI4` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:984:40
    |
984 |                 VT_UI4 | VT_UINT    => VarI8FromUI4(self.get_data().ulVal)?,
    |                                        ^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarI8FromUI8` in this scope
   --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:985:32
    |
985 |                 VT_UI8      => VarI8FromUI8(self.get_data().ullVal)?,
    |                                ^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarR4FromBool` in this scope
    --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:1014:32
     |
1014 |                 VT_BOOL     => VarR4FromBool(self.as_bool())?,
     |                                ^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarR4FromCy` in this scope
    --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:1015:49
     |
1015 |                 VT_CY       => variant_as_type!(VarR4FromCy, f32, self.as_currency()),
     |                                                 ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarR4FromDate` in this scope
    --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:1016:32
     |
1016 |                 VT_DATE     => VarR4FromDate(self.get_data().date)?,
     |                                ^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarR4FromDec` in this scope
    --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:1017:32
     |
1017 |                 VT_DECIMAL  => VarR4FromDec(&self.as_decimal())?,
     |                                ^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarR4FromDisp` in this scope
    --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:1018:56
     |
1018 |                 VT_DISPATCH => dispatch_as_type!(self, VarR4FromDisp),
     |                                                        ^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarR4FromI1` in this scope
    --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:1019:32
     |
1019 |                 VT_I1       => VarR4FromI1(self.get_data().cVal)?,
     |                                ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarR4FromI2` in this scope
    --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:1020:32
     |
1020 |                 VT_I2       => VarR4FromI2(self.get_data().iVal)?,
     |                                ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarR4FromI4` in this scope
    --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:1021:36
     |
1021 |                 VT_I4 | VT_INT  => VarR4FromI4(self.get_data().lVal)?,
     |                                    ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarR4FromI8` in this scope
    --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:1022:32
     |
1022 |                 VT_I8       => VarR4FromI8(self.get_data().llVal)?,
     |                                ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `VarR4FromR8` in this scope
    --> /Users/vallahiboyle/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uiautomation-0.12.0/src/variants.rs:1024:32
     |
1024 |                 VT_R8       => VarR4FromR8(self.get_data().dblVal)?,
     |                                ^^^^^^^^^^^ not found in this scope

```
(just an excerpt)

If I go back to <0.12 then I can not update to windows 0.58 because I use types I retrieve from uiautomation and pass it to windows apis sometimes. Version mismatch is creating a type mismatch for that case.

**Comment by leexgone** [comment]
It is strange that you have this problem, my local environment has not been able to reproduce the same problem.

You can try `cargo update` or `cargo clean`，and rebuild the project.

If there is still a problem, please provide the full `Cargo.toml` file to me

**Comment by elsnerpaul** [comment]
I also had a lot issues after upgrading to 0.12. But the root cause is not this project but windows-rs. They made a lot of symbols only available for windows. Since this made sense to me, not building the windows specific code on other platforms I separated my code now more clearly for the different platforms.
